spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/tenderflex
spring.datasource.username=ruslan-timoshchuk
spring.datasource.password=1234

spring.liquibase.change-log=classpath:db/changelog.xml

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

access.key=euH7MpB1mYQ0W4lKGlKhjCy9qb6cKp72
secret.Key=ylp2imLxLoCghxntK2dcducsuUXLtZvQ
service.endpoint=https://eu-001.s3.synologyc2.net
signing.region=eu-001
bucket.name=tender-flex

allowed.origin.hosts=http://localhost:3000
jwt.token.issuer=tender.flex.com
jwt.access.signing.key=FunpAfQ0cAjjQq6ySQMz9nZJcp9VlX3LdlAy2L4I4Jw
jwt.cookie.max.age=14400
jwt.access.token.live=15m

logging.level.pl.com.tenderflex.repository.impl=DEBUG

##REST API##
api.base.path=/api
api.v1=v1
api.tenders.path=tenders
api.offers.path=offers
api.cpvs.path=cpvs
api.authentication.path=authentication
api.countries.path=countries
api.contract.type.path=contract-types
api.currencies.path=currencies
api.files.path=files